### PR TITLE
make it build

### PR DESCRIPTION
**Pull request by freedomtan**
On Ubuntu 18.04, I can't build the apk with
```
bazel build -c opt  --cxxopt='--std=c++14' \
  --fat_apk_cpu=x86,arm64-v8a,armeabi-v7a \
  //java/org/mlperf/inference:mlperf_app
```
because without this workaround I saw
```
cpp/datasets/coco.cc:42:11: warning: enumeration values 'Int32' and 'Int64' not handled in switch [-Wswitch]
  switch (type) {
          ^
cpp/datasets/coco.cc:52:1: error: control may reach end of non-void function [-Werror,-Wreturn-type]
}
^
1 warning and 1 error generated.
Target //java/org/mlperf/inference:mlperf_app failed to build
```

### CODE REVIEW

**Comment by thaink** [comment]
Thanks for raising this bug.
However, currently we are suffering from an issue while trying to run checks on your PR:
https://github.com/actions/checkout/issues/23
I submitted a PR to fix that. So could you sync this PR with the latest MLPerf master to check if the tests are ok now? Thanks for your help.

**Comment by freedomtan** [comment]
@thaink thanks. rebased. let's see if it goes.

**Comment by freedomtan** [comment]
@thaink still failed. but it seems it's different problem.

**Comment by thaink** [comment]
Thanks. I believe it failed due to Github runtime's instability. Let me check how to fix it.

**Comment by thaink** [comment]
I experienced this error once before. I re-run the test and it was ok. However, It does not work on this PR. I don't think there is any differences here.

**Comment by thaink** [comment]
The build should be successful with the a recent fix.
Can you sync this PR?

**Comment by freedomtan** [comment]
@thaink it works 👍

**Comment by thaink** [comment]
Thanks for your patience, Could you merge this PR?

**Comment by freedomtan** [comment]
nope, I don't have write access.

**Comment by thaink** [comment]
Thanks. Let me merge it.

**Pull request merged**
