### PR TITLE
Adding initial version of the source code

### PR DESCRIPTION
**Pull request by thaink**
- Add the latest version of the code
- Format the README file with clang-format
- Update the prebuilt APK

### CODE REVIEW

**Comment by jdduke** [comment]
@petermattson how would you want to proceed with this?

**Comment by thaink** [comment]
There is another big pull request coming up for the C++ code refactoring.
If you want to review a single chunk of code, I can combine that one with this.
But that will take some time since that work is under review.

**Comment by petermattson** [comment]
Just got back from vacation. Sorry about the permissions issues. Jared,
Terry, and Vijay all now have admin permissions and can merge future PRs
(happy to add more folks). I merged all outstanding PRs, including minor
conflict in README. Thanks for all the hard work! :-)

**Comment by terryheo** [comment]
@petermattson could you merge this PR? The merge menu isn't available for me.

**Comment by petermattson** [comment]
Merged. Also, found one more permission issue and you should be able to
merge now. Can you confirm?
Thanks very much for making this happen!

**Comment by thaink** [comment]
There are some typos but they will be fixed in the next cl.

**Pull request merged**
